
[project]
# PEP 621 project metadata
# See https://www.python.org/dev/peps/pep-0621/
name = "gppt4gui"
version = "0.1.0"
description = ""
authors = [
    {name = "Eric Simmons", email = "noreply"},
]
dependencies = [
    "Flask>=3.0.1",
    "openai==0.28.0",
]
requires-python = ">=3.8"
